### ISSUE TITLE
Design doc review #1 - MVP list and Schema

### ISSUE THREAD

**Issue by aracpyon** [gigimscarborough/FullPlate#1]
**MVP**
- [x] Add dates for each MVP
- [x] (User auth) Users will see error messages when login/signup fails
- [x] (User auth) Make sure to have a sign out button
- [x] (User auth) Use this [resource](https://open.appacademy.io/learn/swe-in-person-nyc/full-stack-project/modalbnb)  for modal
- [x] (Create & Search) You will also build main page while working on this MVP
- [x] (Reviews) If you want users to be able to upload images, you have to set up AWS for it.(Check the resource below under Schema)
- [x] Ratings and Reviews are one MVP together
- [x] You will work on the production README on Friday(1/29) in the morning before the presentation

**Schema**
- [x] Give some extra information on each table(which column is unique, foreign key, what associations like belongs to, has many etc)
- [x] (restaurants) remove `ratings`, `image_url` columns. Ratings is handled by `reviews` table and `image_url` will be handled from AWS or put images on window. Check out these resources: [AWS](https://open.appacademy.io/learn/swe-in-person-nyc/full-stack-project/active-storage-and-aws-s3-hosting-demo), [asset-pipeline](https://open.appacademy.io/learn/swe-in-person-nyc/full-stack-project/understanding-the-asset-pipeline) 
- [x] (reviews) OpenTable review has criteria like Overall, Food, Service, Ambience, Value, Noise level. Consider make these as columns and `rating` will be the average score of all these columns. 
- [x] (favorites) your favorites table looks good to me.

**Comment by gigimscarborough** [comment]
Completed all assigned corrections

**Comment by aracpyon** [comment]
Great job! Now just one more thing. 
**Schema**
- [x] Remove `rating` column from `Reviews`. You wouldn't need this column because it will be the average of values of Overall, Food, Service, Ambience, Value, Noise level. All you have to do is calculate the average before printing it on the browser.

**Comment by gigimscarborough** [comment]
rating has been removed and broken into specific rating columns!
