### ISSUE TITLE
Design doc review #2 - Sample state

### ISSUE THREAD

**Issue by aracpyon** [gigimscarborough/FullPlate#2]
**Sample State**
- [x] Update sample state based on the changes of your schema 
- [x] add `last_name` to users entities 
- [x] `city_id` for restaurant?
- [x]  Don't need restaurantsReserved because you only need reservations for the current user and `Reservations` state will handle it. 
- [x] You don't need `localRestaurants`
- [x] Remove all the states you don't have as `tables` in your DB from entities. Basically, entities represent your tables in DB. And you don't have tables like `localRestaurants`.

**Comment by gigimscarborough** [comment]
Made all necessary changes to the sample state!

**Comment by aracpyon** [comment]
Awesome job Gigi! One small thing. 
- [x] Add `Overall`, `Food`, `Service`, `Ambience`, `Value`, `Noise level` to your reviews slice and remove `rating`

**Comment by gigimscarborough** [comment]
Completed!

**Comment by aracpyon** [comment]
- [x] I also see the `rating` under the restaurant. Remove that too!

**Comment by gigimscarborough** [comment]
awesome! got it! should be gone now!
