### ISSUE TITLE
Design doc review #2 - Backend and Frontend Routes

### ISSUE THREAD

**Issue by aracpyon** [gigimscarborough/FullPlate#3]
**Backend**

- [x] (restaurants) You will also need a custom route for `search`. Google how to make a custom route on rails and make a search route that returns the list of restaurants based on the keyword the user's given us. 

**Frontend**
- [x] (NavBar) OpenTable's navbar is dynamic depending on which route you are on. If the user is on the splash, there is no search bar on the navbar (because there is a big search bar at the center) but once the user is on the restaurant's showpage, the search bar appears on the navBar. This means that they made a navbar component but rendering different elements based on which page the user is on. To do this, navBar component should be imported as a subcomponent for each big component and render different stuff based on what props they are getting. 
- [x] `/` landing page's navbar should be different based on existence of currentUser. If there is no currentUser, there will be `sign up` and `log in` buttons, and if there is, it will print icons on the right side. 
- [x] You don't need `/signup` and `/login` because you are going to use `modals` on the splash page
- [x] `/users/:userId` Make sure only the currentUser can access to only THEIR user's show page. Other users are not allowed to see other users' profile page.

**Comment by gigimscarborough** [comment]
completed necessary changes on routes!

**Comment by aracpyon** [comment]
Perfect. Great job! Make sure to look at these design docs and my comments while you build your final project!
